apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservations-service
  template:
    metadata:
      labels:
        app: reservations-service
    spec:
      containers:
        - name: reservations-service
          image: "mic029/reservations_service:latest"
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://reservations-db.ci2b1rshho7r.us-east-1.rds.amazonaws.com:5432/reservationsDb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_QpWsTlkgt"
            - name: EVENT_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/606529675772/analytic_event_queue"
            - name: RESTAURANTS_SERVICE_URL
              value: "http://172.20.125.223:8080"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: reservations-service
spec:
  selector:
    app: reservations-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: reservations-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: reservations-service
