apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: "259136/restaurant_service:latest"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://restaurant-db.cynj7nxjfjns.us-east-1.rds.amazonaws.com:5432/restaurantDb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: value2
            - name: EVENT_QUEUE_URL
              value: value2
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: restaurant-service
  