apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurants-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurants-service
  template:
    metadata:
      labels:
        app: restaurants-service
    spec:
      containers:
        - name: restaurants-service
          image: "259136/restaurant_service:latest"
          env:
            - name: SPRING_DATASOURCE_URL
              value: <PLACEHOLDER>
            - name: SPRING_DATASOURCE_USERNAME
              value: <PLACEHOLDER>
            - name: SPRING_DATASOURCE_PASSWORD
              value: <PLACEHOLDER>
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: <PLACEHOLDER>
            - name: EVENT_QUEUE_URL
              value: <PLACEHOLDER>
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: restaurants-service
spec:
  selector:
    app: restaurants-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: restaurants-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: restaurants-service
  